### ISSUE TITLE
Shape

### ISSUE THREAD

**Issue by AlexEne** [BrainiumLLC/bodymovin-rs#1]
Hello,

This is fantastic. Thanks you so much for releasing this, as I was looking into building something similar. It's a bit unfortunate that there's so little detail on the format except the one you linked in the readme and some [python lottie docs](https://mattbas.gitlab.io/python-lottie/group__Lottie.html)

I noticed that the `Shape` definitions here are different from previous attempts at a shape in [pathfinder](https://github.com/servo/pathfinder/blob/master/lottie/src/lib.rs):
 
```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "ty")]
pub enum Shape {
    #[serde(rename = "gr")]
    Group {
        #[serde(rename = "it")]
        items: Vec<Shape>,
        #[serde(rename = "nm")]
        name: String,
    },
    #[serde(rename = "sh")]
    Shape {
        #[serde(rename = "ks")]
        vertices: ShapeVertices,
        #[serde(rename = "d")]
        #[serde(default)]
        direction: Option<i64>,
    },
    #[serde(rename = "fl")]
    Fill {
        #[serde(rename = "nm")]
        #[serde(default)]
        name: Option<String>,
        #[serde(rename = "o")]
        #[serde(default)]
        opacity: Option<PropertyValue>,
        #[serde(rename = "c")]
        color: MultidimensionalPropertyValue,
    },
    #[serde(rename = "tr")]
    Transform {
        #[serde(rename = "r")]
        rotation: PropertyValue,
        #[serde(rename = "sk")]
        skew: PropertyValue,
        #[serde(rename = "sa")]
        skew_axis: PropertyValue,
        #[serde(rename = "p")]
        position: MultidimensionalPropertyValue,
        #[serde(rename = "a")]
        anchor_point: MultidimensionalPropertyValue,
        #[serde(rename = "s")]
        scale: MultidimensionalPropertyValue,
    },
    #[serde(other)]
    Unimplemented,
}
```

Right now, `Transform`,`Shape`,`Group` are separate structs rather than enum variants. 
How do you feel about unifying them under an enum in a similar way to how Pathfinder is treating them? It may make deserializing shapes easier.

**Comment by francesca64** [comment]
I'm really glad this is useful for you! Thanks so much for opening this.

I totally didn't know Pathfinder had experimental Lottie/Bodymovin support! (Also, hopefully Pathfinder lives on, since it's awesome!)

I think this is already covered by `AnyShape`? https://github.com/BrainiumLLC/bodymovin-rs/blob/cb56b0f03d127f9f9946c7dbff685dd1e4524aef/src/shapes/mod.rs#L32-L59

**Comment by AlexEne** [comment]
Oh right, I've missed anyshape. Thanks for mentioning it.
